workflows:
  flutter-web:
    name: Performance testing
    environment:
      flutter: dev
    scripts:
      - name: Get flutter packages
        script: |
          brew unlink dart
          brew install --head dart
          cd . && flutter packages pub get
      - name: Run benchmarks
        script: |
          dart test/run_benchmarks.dart
    publishing:
      email:
        recipients:
          - sbis1999@gmail.com
