workflows:
  flutter-web:
    name: Performance testing
    environment:
      flutter: dev
    scripts:
      - name: Switch to dart dev
        script: |
          brew unlink dart
          brew install --head dart
      - name: Enable flutter web
        script: |
          flutter config --enable-web
      - name: Get flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Run benchmarks
        script: |
          dart test/run_benchmarks.dart
    artifacts:
      - report.json
      - build/web/
    publishing:
      email:
        recipients:
          - sbis1999@gmail.com
