workflows:
  flutter-web:
    name: Performance testing
    environment:
      flutter: dev
    scripts:
      - name: Get flutter packages
        script: |
          brew unlink dart
          brew install --head dart
          flutter config --enable-web
          cd . && flutter packages pub get
          cd . && pub global activate junitreport
      - name: Run benchmarks
        script: |
          flutter test --machine | tojunit --output report.xml test/run_benchmarks.dart
    publishing:
      email:
        recipients:
          - sbis1999@gmail.com
