workflows:
  flutter-web:
    name: Performance testing
    environment:
      flutter: dev
    scripts:
      - name: Switch to dart dev
        script: |
          brew unlink dart
          brew install --head dart
      - name: Enable flutter web
        script: |
          flutter config --enable-web
      - name: Get flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Activate JUnit Report
        script: |
          cd . && pub global activate junitreport
      - name: Run benchmarks
        script: |
          flutter test --machine test/run_benchmarks.dart | tojunit --output report.xml
    artifacts:
      - report.xml
      - report.json
      - build/web
    publishing:
      email:
        recipients:
          - sbis1999@gmail.com
